// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hub} from '../models';

export function CreateCommandLineTool(arg1:hub.CommandLineTool):Promise<number|string>;

export function CreateServiceTool(arg1:hub.ServiceTool):Promise<number>;

export function GetDirs():Promise<hub.Dirs>;

export function UpdateCommandLineTool(arg1:hub.CommandLineTool):Promise<boolean>;

export function UpdateServiceTool(arg1:hub.ServiceTool):Promise<boolean>;

export function UpdateTool(arg1:hub.Tool):Promise<boolean>;
