// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCommandLineTool(arg1) {
  return window['go']['hub']['Model']['CreateCommandLineTool'](arg1);
}

export function CreateServiceTool(arg1) {
  return window['go']['hub']['Model']['CreateServiceTool'](arg1);
}

export function GetDirs() {
  return window['go']['hub']['Model']['GetDirs']();
}

export function UpdateCommandLineTool(arg1) {
  return window['go']['hub']['Model']['UpdateCommandLineTool'](arg1);
}

export function UpdateServiceTool(arg1) {
  return window['go']['hub']['Model']['UpdateServiceTool'](arg1);
}

export function UpdateTool(arg1) {
  return window['go']['hub']['Model']['UpdateTool'](arg1);
}
